local P = require("tepidarium.palette")
local D = require("tepidarium.palette_derived")

return function()
  return {
    Normal       = { fg = P.fg, bg = P.bg },
    NormalNC     = { fg = D.ui_muted, bg = P.bg },
    NormalFloat  = { fg = P.fg, bg = D.ui_surface },
    FloatBorder  = { fg = D.ui_border, bg = D.ui_surface },
    FloatTitle   = { fg = P.fg, bg = D.ui_surface, bold = true },
    Comment      = { fg = D.ui_muted, italic = true },
    CursorLine   = { bg = P.bg },
    CursorLineNr = { fg = P.yellow, bold = true },
    LineNr       = { fg = D.ui_muted },
    Visual       = { bg = P.bright_black },
    Search       = { reverse = true },
    IncSearch    = { reverse = true },
    CurSearch    = { reverse = true },
    MatchParen   = { fg = P.cyan, bold = true },
    Pmenu        = { fg = P.fg, bg = D.ui_surface },
    PmenuSel     = { fg = P.fg, bg = P.blue, bold = true },
    PmenuSbar    = { bg = D.ui_surface },
    PmenuThumb   = { bg = D.ui_border },
    StatusLine   = { fg = P.fg, bg = P.bg },
    StatusLineNC = { fg = D.ui_muted, bg = P.bg },
    WinSeparator = { fg = D.ui_border },
    VertSplit    = { fg = D.ui_border },
    Title        = { fg = P.blue, bold = true },
    Directory    = { fg = P.blue },
    ErrorMsg     = { fg = P.red, bold = true },
    WarningMsg   = { fg = P.yellow },
    MoreMsg      = { fg = P.green },
    Question     = { fg = P.green },
    NonText      = { fg = P.bright_black },
    Whitespace   = { fg = P.bright_black },
    SpecialKey   = { fg = P.bright_black },
    Folded       = { fg = D.ui_muted, bg = D.ui_surface },
    FoldColumn   = { fg = D.ui_muted, bg = P.bg },
    SignColumn    = { bg = P.bg },
    ColorColumn  = { bg = D.ui_surface },
    CursorColumn = { bg = D.ui_surface },
    WildMenu     = { fg = P.fg, bg = P.blue, bold = true },
    WinBar       = { fg = P.fg, bg = P.bg, bold = true },
    WinBarNC     = { fg = D.ui_muted, bg = P.bg },
    TabLine      = { fg = D.ui_muted, bg = P.bg },
    TabLineFill  = { bg = P.bg },
    TabLineSel   = { fg = P.fg, bg = D.ui_surface, bold = true },
    DiffAdd      = { fg = P.green },
    DiffChange   = { fg = P.yellow },
    DiffDelete   = { fg = P.red },
    DiffText     = { fg = P.yellow, bold = true },
    SpellBad     = { sp = P.red, undercurl = true },
    SpellCap     = { sp = P.yellow, undercurl = true },
    SpellRare    = { sp = P.cyan, undercurl = true },
    SpellLocal   = { sp = P.green, undercurl = true },
  }
end
