local P = require("tepidarium.palette")

return function()
	return {
	    Comment = { fg = P.white, },
	    Constant = { fg = P.magenta },
	    String = { fg = P.orange },
	    Character = { fg = P.magenta },
	    Number = { fg = P.bright_magenta },
	    Boolean = { fg = P.purple },
	    Float = { fg = P.bright_magenta },
	    Identifier = { fg = P.white },
	    Function = { fg = P.yellow },
	    Statement = { fg = P.magenta },
	    Conditional = { fg = P.magenta },
	    Repeat = { fg = P.magenta },
	    Label = { fg = P.magenta },
	    Operator = { fg = P.bright_white },
	    Keyword = { fg = P.magenta },
	    Exception = { fg = P.red },
	    PreProc = { fg = P.red },
	    Include = { fg = P.magenta },
	    Define = { fg = P.red },
	    Macro = { fg = P.red },
	    PreCondit = { fg = P.red },
	    Type = { fg = P.green },
	    StorageClass = { fg = P.green },
	    Structure = { fg = P.green },
	    Typedef = { fg = P.green },
	    Special = { fg = P.purple },
	    SpecialChar = { fg = P.purple },
	    Delimiter = { fg = P.bright_white },
	    SpecialComment = { fg = P.white },
	    Underlined = { underline = true },
	    Bold = { bold = true },
	    Italic = { italic = true },
	    Error = { fg = P.red },
	    Todo = {
	      bg = P.background,
	      fg = P.orange,
	      bold = true,
	    },
	    javaAnnotation = { fg = P.yellow },
	  }
end
